kano_settings/system/display.py

KanoComputing/peldins#1531
The monitor edid parsing would fail if it is detected that the device is
CEA but the screen size detection fails. Adds a more resilient method to
compare the screen size. Also adds an extra check to detect if it is a
monitor or a television - if the model name includes 'TV' then it is a
good indication that the device is a television.

Make the monitor edid parsing more resilient

---

debian/control
kano_settings/system/advanced.py

KanoComputing/peldins#1543
Currently, if the parental controls are enabled and the interface
obtains a new network configuration via DHCP, the parental DHCP servers
will be replaced by the DNS servers from DHCP. Resolvconf allows finer
control over which DNS servers are used, providing the ability to
prevent DNS servers configured by DHCP from being used.
This patch fixes the problem by changing the DNS settings through
resolvconf and disabling DHCP DNS servers when parental DNS is being
used.

Switch to use resolvconf for setting DNS

---

bin/kano-wifi

* Plugging the wireless dongle will only reboot the unit
on RaspberryPI models A and B. This change removes
this warning message for all other models.
cc  @pazdera @FMog

Fixing a warning message when plugging the wifi dongle

---

kano_settings/set_about.py
kano_settings/system/about.py
kano_settings/system/account.py
kano_settings/system/advanced.py
kano_settings/system/display.py
kano_settings/system/proxy.py
kano_settings/system/wallpaper.py

Originally, this was only about `about.py` to make translating strings easier for later gettext use by using a consistent string templating engine throughout the code.
Ok, admittedly the rest of this patch is bike-shedding. Not long ago, Python docs used to tell programmers that [% is deprecated and one should use .format() instead](https://docs.python.org/release/3.1.5/library/stdtypes.html#old-string-formatting-operations). But that warning [has been removed from newer Python docs](https://docs.python.org/3.5/library/string.html#formatspec) and so it looks like % isn't calling in the Spanish Inquisition these days.
But still.

use .format() instead of %

---

bin/kano-settings
debian/changelog
debian/kano-settings.postinst

kano-stop-splash from settings.
Although it would be safe for kano-world to launch without this change,
the splash would temporarily cover the UI so we bump the version
of kano-settings to allow kano-profile to depend on it.
We also need to allow the splash identifier variables to pass to
kano-settings when it is run using sudo, for which purpose the sudoers
file is modified.

To allow kano-world-launcher to have a splash screen, we need to call

---

bin/kano-settings
kano_settings/set_account.py
kano_settings/set_advanced.py
kano_settings/set_overclock.py
kano_settings/set_wifi.py

Most of Kano code uses KanoDialog with a dictionary to describe the buttons. But that can be a problem:
response = KanoDialog(
title_text = "Now click:",
description_text = "Click a button.\nBut choose wisely.",
button_dict={
'#1': {
'color': 'green',
'return_value': 1
},
'#2': {
'color': 'red',
'return_value': 2
},
'#3': {
'color': 'orange',
'return_value': 3
},
'#4': {
'color': 'grey',
'return_value': 4
}
}
).run()
results in this:
...because items in a dictionary are stored with a hash and the items' order is undefined.
A side effect for i18n is that the button order can be different for different locales:
response = KanoDialog(
title_text = _("Reboot?"),
description_text = _("Reboot required."),
button_dict={
_("Later").upper(): {
'color': 'grey',
'return_value': False
},
_("Reboot …

KanoDialog: use array instead of dict explicit button ordering

---

etc/init.d/kano-bootup-sound

* Missing include file for LSB init scripts (log_msg and friends)
* Fixed order of redirection parameter for aplay
This minor issues caused garbage noise to be displayed to the boot console.
cc @alex5imon @Ealdwulf @pazdera

Bootup sound script is displaying warning messages

---

kano_settings/set_overclock.py
kano_settings/system/overclock.py

This fixes some errors which prevent kano-settings-onboot from working correctly.

Fix name errors

---

bin/kano-settings-onboot
kano_settings/system/display.py

This PR should fix #1723 . If we detect 640x480 mode, we use the same path as the 'safe mode' keys to reboot in 1024x768.

Prevent 640 480

---

bin/kano-settings
debian/control

This happens when the window is closed, sending off the current
* audio configuration,
* display setup
* and parental lock level.
Depends on the new tracker in profile.
Related to: https://github.com/KanoComputing/peldins/issues/1661
cc @carolineclark @alex5imon 
Tested on the pi and it seems to be working.

bin: Emit a tracking event

---

debian/changelog
kano_settings/set_account.py
kano_settings/system/account.py

Changing to the new kano-init interface.
I made all the imports conditional and while that's not ideal, there shouldn't be any problems with compatibility.
cc @alex5imon

Moving settings to use the new kano-init API

---

kano_settings/system/audio.py

Originally, 'numid' was being used to set the PCM control value but this
can vary between systems so use the name instead. Also default to
reporting analogue if the value retrieved when checking is not
recognised.
cc @Ealdwulf

Audio: Identify the ALSA control device by name

---

kano_settings/set_keyboard.py

This PR sets the default country to the first one in the available list. This way after changing the continent instead of getting empty dropdown menus for country and consequently for the "advanced options"

Set default value for Country dropdown

---

etc/rc.overclock

* Even thought KanoOS kernel has it by default,
we are forcing the "ondemand" operation mode to the rest
of the CPU cores

Enabling ondemand mode to RPI2 4 CPU cores

---

bin/kano-wifi-gui
kano_wifi_gui/NetworkScreen.py
lxpanel-plugin-internet/kano_internet.c

The command ```sudo kano-wifi-gui --disconnect``` will now disconnect the user from the internet if they are connected to WiFi.
Added a disconnect option to the internet widget.
When clicking disconnect, this launches a dialog once the process is finished:
Added a beautiful Disconnect button to the GUI when the user is connected via WiFi.  Will change when @TommySaehl has a design, the placement does look a bit weird.
This is nearly complete, but needs some more refining with ethernet connections - for example, the Disconnect option in the internet widget should only be shown when connected to WiFi.
Needs this pull request to work: https://github.com/KanoComputing/kano-toolset/pull/131

Add disconnect wifi option

---

kano_settings/system/audio.py

The correct call is `logger.warn`.
cc @pazdera

Fix mislabelled call to 'logger.warning'

---

kano_settings/system/locale.py
tests/__init__.py
tests/i18n/__init__.py
tests/i18n/test_locale.py
tests/test.py
tests/tools.py

To enable use of locales, add the functions which provide the ability to
set them using the settings toolset. This adds a functions to manage the
locales (installation, removal, setting the locale, checking that the
locale is valid, etc) and also provides unit tests to check each of
these functions.
@pazdera @convolu @skarbat

i18n: Add functionality (and tests) to set locale

---

bin/kano-wifi-gui
kano_wifi_gui/NetworkScreen.py
kano_wifi_gui/PasswordScreen.py
media/kano-connect/CSS/kano_wifi_gui.css

- Disables checkbutton and password entry
- WiFi window should always stay on top
- GUI should only appear to be connected to a network if it has internet.
https://github.com/KanoComputing/peldins/issues/1864
https://github.com/KanoComputing/peldins/issues/1863
https://github.com/KanoComputing/peldins/issues/1861
https://github.com/KanoComputing/peldins/issues/1862

Changes to WiFi GUI

---

bin/kano-settings
debian/control
kano_settings/home_screen.py
kano_settings/main_window.py
kano_settings/screens.py

- Moves the management of screen icons into a separate file
- Reimagines the home screen code structure
- Splits the main window class from the executable
- Allows launching screens from the CLI using either the screen name or the (to be deprecated) screen number.
- Installs the i18n libraries
I'm not quite satisfied with the `ScreenCollection` class - we need:
- Elements to be ordered
- Elements accessible by name
- Elements accessibly by index (although this will be deprecated at some point)
cc @convolu @pazdera @carolineclark Thoughts? Comments?

Home refactor

---

bin/kano-connect
debian/kano-connect.postrm

* When the ethernet cable is plugged in, kano-connect will still
try to associate wirelessly if a control file is found (force multihomed mode)

Allow kano-connect to proceed even if Ethernet cable

---

kano_settings/no_internet_screen.py

The event connected to the 'later' button on the no internet screen was
malformed which would result in the event handler not being triggered.
cc @carolineclark @pazdera

No Internet Screen: Fix 'later' button

---

bin/kano-connect

This PR fixes a syntax error on `master` due to an unquoted string.

Fix unquoted string.

---

kano_settings/system/get_username.py

When the kano kit boots for the first time, kano-init complains with `unable to resolve host kano`.
On the build logs there's an execption `KeyError: 'getgrnam(): name not found: kanousers'`.
This changeset controls this exception to return None, so the code proceeds correctly.
@Ealdwulf @alex5imon

Fixing get_username when Kit boots for the first time

---

kano_settings/system/advanced.py

This PR should fix the warning about unknown host 'kano' introduced by #274 I have taked the approach of leaving 'kano' in '/etc/hosts' as the effect of restarting internet looked unpredictable.
@skarbat

Fix hostname

---

kano_settings/system/advanced.py

KanoComputing/peldins#1919
Although the parental level can be retrieved through `config_file`'s
`get_setting` function, this is intended for use solely within Kano
Settings (for the UI). Also, to get the correct setting, a combination
of `get_setting` and checking if the parental controls are enabled at
all is required to get the correct setting so add a function to allow
the setting to be retrieved by third parties.
@alex5imon It is much easier to add a function to do this rather
than rework how the value is handled internally to Settings and
configure the update scenarios for every user. If you would like
the function to behave differently then let me know.

Parental: Add function to retrieve parental level

---

bin/kano-safeboot-mode
bin/kano-settings-onboot
debian/kano-settings.install
debian/kano-settings.postinst
etc/init.d/kano-safeboot
etc/init.d/kano-settings
kano_settings/boot_config.py
kano_settings/system/display.py

This PR splits kano-settings-onboot into two parts so one part can be run before lightdm while the remaining part can be run after but take more time.

Split kano-settings-onboot

---

etc/init.d/kano-settings

@alex5imon This PR foces kano-settings-onboot to run before lightdm 
It also adds some standard init boiler-plate which adds a message showing it running  in the same way as all the other scripts in init.d, and prevents it being called with 'stop'). 
However, it turns out that kano-settings-onboot takes about 15 seconds to run. Therefore maybe we don't want to run it before lightdm because doing so may prevent the desktop for 15 more seconds appearing in the case where we are not going to reboot. Thoughts @pazdera @skarbat @tombettany ?

Make kano-settings-onboot run before lightdm.

---

kano_settings/parental_config.py
kano_settings/set_wifi.py

* The function to open the common browser was being referenced
as a Gtk callback method, which would never work. Added a callback
function which correctly calls the function to open the browser
cc @alex5imon @Ealdwulf

Fixed opening Browser login from wireless settings

---

kano_settings/system/advanced.py

@alex5imon 
The action function for the parental control checkbox (set_parental_enabled)
was only setting or restoring the hosts file, this PR changes it to call
set_parental_level to save/restore all parental control functionality.

Fix parental control checkbox

---

kano_wifi_gui/NetworkScreen.py

* The wireless cached credentials were not being removed on disconnect,
so the desktop network plugin would quickly reconnect back to wireless.

Added missing wifi cache cleanup on disconnect

---

kano_settings/system/advanced.py

When setting the parental setting to Medium or High, the ultimate
parental setting code would revert the DNS servers to Google's, not
OpenDNS's. Rectify this by running the parental DNS configuration after
the ultimate parental code so that they don't get overwritten.
@FMog Built on `scratch` for you to test.
@carolineclark @convolu Could you review.
cc @alex5imon

Parental: Fix setting DNS for Medium and High settings

---

etc/init.d/kano-safeboot
etc/init.d/kano-settings

This PR adds a dependency to kano-safeboot-mode and kano-settings-onboot to wait for the filesystem to be remounted read/write. For safeboot mode this only affects logging, possibly without this  kano-settings-onboot woudl break if it was run too early, although I'm not sure if /boot actually gets mounted readonly at the start of time or not.
It is possible that there are other missing dependencies For example if we depend on some device then we should also ensure that it has been initialised. However I can't see any obvious missing ones...
@skarbat @pazdera @tombettany

Add dependencies on $local_fs, which is necessary for logging to work.

---

kano_settings/system/font.py

This PR removes a call to `lxsession -r` which is no longer needed in the version of
LXDE on jessie (and causes problems). This is still needed on wheezy, so can't
be merged on master. Note this may mean we should add a dependency for a later version
of lxsession.
However kano-settions doesn't currently have a dependency on lxssession, should it be added?
@pazdera @tombettany @radujipa

Fix font settings panel not to invoke init flow

---

kano_settings/system/advanced.py

This PR speeds up kano-init finalise from ~6 to ~2 seconds.
It does this by moving the import of pycountry into the function that uses it.
@alex5imon @tombettany

Speed up kano-init finalise

---

kano_settings/parental_config.py
kano_settings/templates.py

This PR includes a slightly better sanitation for supplied websites.
Apart from removing the `www.` at the beginning it also removes everything after the first `/`
e.g. `www.reddit.com/r/subreddit` becomes `reddit.com`
Related to https://github.com/KanoComputing/peldins/issues/2076
@pazdera @tombettany Could you please review this?

Enhanced website sanitation to include slashes

---

kano_settings/system/display.py

* Some displays may return garbage data when querying EDID info
on the model name data field. Fixed by sanitizing the returned string.
cc @Ealdwulf @alex5imon

Fixed random exceptions on particular displays

---

bin/kano-checked-reboot
bin/kano-safeboot-mode
bin/kano-settings-onboot
debian/changelog
debian/kano-settings.install
debian/kano-settings.postinst
etc/init.d/kano-reboot-clear

@alex5imon @convolu 
This PR prevents an unlimited number of reboots. It contains:
* A wrapper script for systemctl reboot. This builds up sentinel files per reboot and refuses to work
if there are too many. It also does sync itself, so I have removed that from call locations.
* An init script which clears the sentinels, when it appears that the system has settled.
It appears to be unavoiable that we have a timeout-based heuristc to see if teh system has settled. 
I have made this 5 minutes. That means that if someone changes there settings quickly, it won't have an effect due to refusing a reboot. Any opinions on the correct period? @FMog, I guess you are most likely to be bitten by this! 
I have set the max number of reboots at 3 (because I know kano-init reset can cause this scenario). …

Limit reboots

---

kano_settings/system/advanced.py

KanoComputing/peldins#2175
When attempting to connect to WiFi, with ultimate parental controls
enabled and the sentry server not running, the GUI can hang despite
having fully established a connection. This is because launching the
sentry server was done in a way that it was waiting on stdin. Resolve
this by explicitly declaring the stdin source.
Supersedes https://github.com/KanoComputing/kano-settings/pull/330
@convolu @Ealdwulf Can we try this again?

Parental: Prevent hanging when starting sentry server

---

kano_settings/parental_config.py
kano_settings/system/advanced.py

If the ultimate parental control has been set and disabled without
updating the config file, then the script that starts the Sentry server
reports that parental control is enabled and thus network settings don't
get properly set. Resolve this by writing the change to the config file
every time some change occurs to the parental setting.
cc @convolu @Ealdwulf

Parental: Ensure parental setting gets updated

---

bin/kano-safeboot-mode
bin/kano-settings-onboot
debian/changelog
debian/control
kano_settings/boot_config.py
kano_settings/default.py
kano_settings/set_display.py
kano_settings/set_overclock.py
kano_settings/system/audio.py
kano_settings/system/display.py
tests/boot_config/__init__.py
tests/boot_config/test_config.py
tests/boot_config/test_lock.py
tests/test.py

This PR changes the settings API to be transactional, and changes the settings tools to use it.
All changes are applied to temporary file in `/boot`, which is moved into place at the end. This will hopefullly prevent the 'empty config file' problem.
All the functions which write  to `/boot/config.txt` will no longer take effect until a call to end_config_transaction(). This includes things like `safe_mode_restore_config`as well as the more obvious ones.  Note that read functions as well as write functions start a transaction. During a transaction, a lock is held so any access by other processes will wait (for up to 5 seconds) and then time out. This wait is in case the boot scripts happen to run at the same time.
This is a bit a bit complicated so APIs used externally to  the …

Config locking

---

bin/kano-settings-onboot
boot_default/config.txt
debian/kano-settings.install
kano_settings/boot_config.py

@alex5imon @skarbat @pazdera 
This PR is for https://github.com/KanoComputing/peldins/issues/2170
It performs simple (not exhaustive) checks on config.txt and restores a default one if anything alarming is seen. Currently, it only checks for the presence of two parameters chosen from different locations  in the file.
This PR makes a copy of the config.txt from peldins. To avoid divergence, I will later make a PR for peldins which copies this file into `/boot` during the build, after kano-setttings has been installed.

Correct corrupt config

---

boot_default/config.txt

@skarbat @pazdera @alex5imon 
This enables the spi device by default.

Enable spi device by default.

---

kano_settings/system/advanced.py

KanoComputing/peldins#2270
When setting the parental level, the GUI setting is saved also with a
prevention mechanism for setting the value too low. This minimum was
maligned with the numbering for the parental setting which prevented the
lowest setting from being configured. Resolve this by correcting the
minimum setting.
cc @pazdera

Parental: Permit setting lowest setting

---

WHITELIST

Kano world will move their images to Cloudinary (http://cloudinary.com/) at some point. Whitelisting it on the OS.
This would break quite a few things (the shares widget, kano apps and kano world when the ultimate parental lock is on).
cc @alex5imon @tombettany @arifshanji @andreiconstantinescu

Whitelisting Cloudinary

---

tests/boot_config/test_config.py

@skarbat This fixes the failure of the QA test for boot_config. I was going to add a test for remove_noobs_defaults(), but I have to work on other stuff.

Fix QA failing test for boot_config

---

bin/kano-settings-cli
debian/control
kano_settings/config_file.py
kano_settings/system/display.py

This PR adds an a way to switch to the new driver, if it is installed, for testing.
There will be another PR for kano-desktop to start xcompmgr if necessary.
It saves `/usr/share/X11/xorg.conf.d/99-fbturbo.conf`, which is actually from `xserver-xorg-video-fbturbo`, in `/var/cache`, and only restores it if there is not one there already (therefore hopefully avoiding overwriting it if it is written by upgrading that package).
@tombettany @radujipa @alex5imon

Add methods to switch to/from the experimental GL graphics driver.

---

bin/kano-settings-onboot

This PR sets x-www-browser to epiphany on pi1 and pi0, and chromium otherwise.
Note that currently it is set to epiphany everywhere but we hardcode chromium. There will be another PR in kano-desktop to switch it in kdesk.
@alex5imon @tombettany

Switch browser

---

boot_default/config.txt

For the time being, increase gpu_mem to 256 to get kano-overworld to work.
See https://github.com/KanoComputing/kano-overworld/issues/26

Increase GPU mem

---

etc/init.d/kano-settings

* The script ensures user is always brought to the Dashboard
* Using a safe soft dependency to the external script

Calling Dashboard Onboot script early in the boot process

---

boot_default/config.txt

This PR reverts the gpu memory increase. Anyone wanting to make a case for 192 please do so, otherwise  will commit this - we have 31Mb of headroom which ought to be enough, although we shoudl keep an eye on it.
@radujipa @alex5imon

Revert gpu mem increase.

---

bin/kano-settings-cli

This PR moves an import to speed up kano-settings-cli
@alex5imon @tombettany
This is for KanoComputing/kano-overworld#215, as if kano-settings-cli can be made fast enough, we don't need to use vcgencmd.

Move a slow import to where it is used.

---

kano_settings/set_keyboard.py

* A thread was started to apply the new changes (read), and right
after that a call to save them was being called (write),
the apply would sometimes crash because the file would be empty.
* Fixed by saving the settings first, then start the thread to apply them.
@Ealdwulf this PR would replace this one: https://github.com/KanoComputing/kano-toolset/pull/208
Tested briefly and seems to fix it. What do you think?

Fixing kano-settings keyboard sometimes failing

---

kano_settings/system/display.py

* Filter out those below 1024x768 so the user cannot select them
from the kano-settings Display section.
* Should fix problems when selecting a lower resolution which is then
automatically increased on next reboot.

Limit display resolutions

---

kano_settings/boot_config.py

Safe mode was unintentionally 'sticky', which I think causes some of the issues seen in https://github.com/KanoComputing/peldins/issues/2346. This PR should fix this.
@skarbat @tombettany

Cleanly terminate safe mode

---

debian/control
kano_settings/system/advanced.py

This PR is intended to fix https://github.com/KanoComputing/peldins/issues/2294. It needs more testing.
Making a PR only to remember why this branch exists and link it to the issue.
- sentry dns is now used for low level as well as ultimate level.
- In low level, sentry is used to map *.(google|youtube).*DOMAIN to
forcesafesearch.google.com
- Cookie manipulation is no longer required
This depends on a patched version of sentry (version 0.5.1) (https://github.com/KanoComputing/sentry/pull/2)

Fix low level parental control

---

debian/control

The `libkano_networking` library was split from the `kano-toolset`
package into its own package. Depend on this package instead.
Required after https://github.com/KanoComputing/kano-toolset/pull/206.

Dependencies: Depend on new libkano-networking package

---

bin/start-sentry-server
debian/changelog
debian/control
kano_settings/system/advanced.py

This PR fixes a few issues missed in merging #360 : 
* sentry wasn't being restarted at boot except in ultimate parental mode (it is now required in all parental control modes except 'off') 
* opendns wasn't being used (because it now needs to be used at the same time as sentry)
Unrelated to #360, changing between different parental control modes wasn't changing the hosts file, so, eg, going to mode 2 wan't adding search engines to the blacklist if you were already in mode 1, because the loging which wrote the hosts file had a check that assumed that the hosts file couldn't need changing if we it was 'already big'.
Therefore when we are in a parental control mode I have added  code to restore the backup hosts file before appending the blacklist. I think this shoudl be okay (after all, we …

Fix sentry startup

---

kano_settings/system/advanced.py

We are updating the parental control whitelist from github, but from the wheezy branch.
If we every merge back to master, this will need to be update again.
@tombettany 
cloudinary.com has been added to the jessie branch of the whitelist, which may be causing some problem. Any idea what it is used for @pazdera @convolu ?

Switch to pulling whitelist from the current branch.

---

kano_settings/screens.py

Setting the wallpaper only works in desktop mode so don't show the
option in dashboard mode.
cc @skarbat

Wallpaper: Hide the option in dashboard mode

---

etc/init.d/kano-bootup-sound
etc/kano-rc.local
kano_settings/system/audio.py

This PR updates kano-settings to use alsa-store instead of the deprecated alsa-utils.
@radujipa 
kano-boot-up sound is also changed to depend on alsa-restore instead of kano-utils.

Use alsa-store instead of the deprecated alsa-utils.

---

kano_settings/system/overclock_chip_support.py

A pi in the workshop was seen to get confused about restoring config.txt because it did not have the fix for https://github.com/KanoComputing/peldins/issues/2366. This PR makes this path more robust in the event that future pis have more revision numbers.
@tombettany @skarbat   
Not necessary to merge for 3.3

Don't change the config if the pi is not recognised

---

bin/kano-settings-cli
kano_settings/system/keyboard_config.py

This PR implements the missing the `set keyboard  --layout` option in kano-settings cli, which is used in the es_AR overnight image build.
It makes set_keyboard save the keyboard setting in /etc/default/keyboard, and also makes it set the console setting.
@skarbat @tombettany

Support for building spanish image with keyboard settings.

---

bin/kano-settings-cli
kano_settings/set_keyboard.py
kano_settings/system/keyboard_config.py
kano_settings/system/keyboard_layouts.py
kano_settings/system/locale.py
tests/i18n/test_locale.py

https://trello.com/c/B07XgJVB/201-get-kano-settings-cli-to-implement-setting-keybaord-layout
The CLI is used to configure the locale settings for the image at build
time. As such, expose the keyboard setting interface and unify it with
the GUI setting.
cc @Ealdwulf

Keyboard locale: Allow setting the keyboard from the CLI

---

tests/boot_config/test_config.py
tests/i18n/test_locale.py
tests/tools.py

When running the tests, there are some which can't be run if the correct
hardware isn't present. Accommodate this by providing a `require_rpi`
decorator for tests.

Tests: Add "require_rpi" flag

---

kano_settings/system/locale.py

The `XSESSION_RC_FILE` file utilises the `get_user_unsudoed()` function
which requires a user to have already been created. This fails on the
build server chroot where no users exist so scope it inside its
utilising function.
Moreover, migrate away from utilising this method for setting the
locale.
cc @Ealdwulf

Locale: Scope XSESSION_RC_FILE to utilising function

---

kano_settings/boot_config.py
kano_settings/system/boot_config/boot_config_line.py
kano_settings/system/boot_config/boot_config_parser.py
tests/boot_config/boot_config_parser.py
tests/boot_config/test_config.py

This PR fixes set_config_value to make sure the setting is uncommented if you call "set_config_value()",
unless the value it is passed is None, in which case it comments out the setting.
* set_config_value() should replace commented out version of the setting.
* Had to extend the representation class (boot_config_line) a bit, to clearly distinguish commented out settings and random comments. Commented out settings always need a '=0'.
Updated the unit test to include commented out settings.
@skarbat @radujipa @tombettany

Fix set to uncomment setting

---

kano_settings/set_keyboard.py
kano_settings/system/keyboard_config.py

Fixes https://trello.com/c/Zf6k4Oy9/73-kano-init-font-is-too-smal
After quite a lot of investigation I found out the reason as to why the console font on the Spanish image is tiny is because, when [setting up the keyboard layout]( https://github.com/KanoComputing/peldins/blob/69ee1718fe5d072c7f158ab06bc97ee20767fb2c/Makefile#L546), `kano_settings` sets the `XKBLAYOUT` in `/etc/default/keyboard` to `es_AR` which is not recognised and so the console setup fails. The fix was to set `XKBLAYOUT` to just `es` which works fine.
I also fixed a bug in the keyboard settings page that prevented it from displaying on the english image.
cc. @Ealdwulf @radujipa

Keyboard setup fixes

---

boot_default/config.txt

Using an RPi2 with a Screen Kit, it was possible somehow for something to get
confused about the display and write the option at the end. What that means is
that kano-settings will change the display_rotate in one of the Screen Kit
filters which gets ignored by the lowest setting that was incorrectly written
at the end of the file outside the filters.
@tombettany @Ealdwulf @skarbat up to you if you want to merge this for the release. I tested it and it seems to be working.

Fix for unresponsive flip display option in Display

---

bin/kano-boot-check
debian/kano-settings.install
debian/kano-settings.postinst
debian/kano-settings.postrm
etc/init.d/kano-boot-check

This PR adds a program `kano-boot-check` which tests whether the plug was pulled.
It is run at bootup with the argument `start` and shutdown with the argument `stop`. 
To determine if the system was shut down properly, look at the return code of `kano-boot-chek test`
which is successful (0) if it was.
@skarbat @radujipa 
This can be used to implement the warning which is planned for the dashboard.
For https://trello.com/c/UiqoXEkb

Add boot check

---

debian/changelog

This PR bumps the version of kano-settings so we can depend on the existence of kano-boot-check.
@skarbat @tombettany

Bump version to allow dependency on new kano-boot-check binary.

---

bin/kano-checked-reboot

Sometimes we call reboot without taking down systemd units, which prevents us from
correctly deciding whether the plug has been pulled. Always shut down kano-boot-check.service.
@tombettany @skarbat

Fix spurious shutdown warnings on forced reboot

---

boot_default/config.txt

Change gpu_mem to 256 for test purposes.
Making the change on the RC for 2 reasons: we want to QA it, and this will also test the rc rebase detection . @tombettany

Test 256mb GPU mem

---

.gitignore
kano_wifi_gui/ConnectToNetwork.py

Bug: 1619 - Wifi No Refresh Issue
Redirect user to the network refresh screens in the gui wifi settings dialogue after a connection failure because of a "weak signal". 
Additionally, modified the .gitignore to include Emacs and VSCode files and dirs.

Refresh networks immediately after a weak signal screen failure.
