KanoComputing/kano-settings

debian/control
lxpanel-plugin-internet/Makefile
lxpanel-plugin-internet/kano_internet.c
lxpanel-plugin/Makefile
lxpanel-plugin/kano_settings.c

Related to: https://github.com/KanoComputing/peldins/issues/1540
cc @alex5imon

widgets: Porting to lxpanel > 0.7.0

---

kano_settings/set_display.py

Display current display resolution below the brand name

---

kano_settings/components/menu_button.py
kano_settings/home_screen.py

The `if len(description) >= 12` isn't necessairy, GtkLabel comes with a built-in function for just that.

use set_ellipsize() for button label

---

kano_settings/set_font.py
kano_settings/set_mouse.py
kano_settings/set_overclock.py
kano_settings/system/font.py
kano_settings/system/mouse.py
kano_settings/templates.py

This simplifies the code for the radio button template and the setttings screens using it.
IMHO, this is easier to read (and easier to translate the config names later).

simplify code to handle radio buttons

---

debian/changelog
kano_settings/set_appearance.py

* At this point only the lxpanel settings are to be restored
* Refreshes the panel so that no logoff is necessary

Adding the functionality to reset Desktop settings

---

debian/control
kano_settings/parental_config.py
kano_settings/system/advanced.py

* Disabling google.com when setting parental control to "high"
* Until we have a higher version of Chromium that supports this sestting in policy files

Chromium safe-search

---

kano_settings/system/advanced.py

* Added list of Google sites reachable via 2 level domains

Fixing parental lock for google sites

---

bin/kano-settings
debian/changelog
kano_settings/home_screen.py
kano_settings/set_appearance.py
kano_settings/set_screensaver.py
kano_settings/set_wallpaper.py
kano_settings/templates.py

Modified the current background selector for the init flow (the changes shouldn't affect the look of the current one).
cc @carolineclark @alex5imon Please review.

Init flow bg selector

---

bin/kano-wifi-gui

* On successfull connection the cache file is saved,
if the connection does not succeed the cache is removed

Telling kano-wifi-gui to save the connection for next boot

---

debian/control

kano-settings should depend on kano-connect

---

kano_settings/system/wallpaper.py

Currently the function for changing the wallpaper takes the path and the
name of the wallpaper. It then constructs the full filename by appending
the path with the name, but it does this without any checking, requiring
either the supplied path to end in a `/` or the supplied name to begin
with a `/`. Instead use `os.path.join` to make this process safer.
cc @carolineclark @convolu

Wallpaper: Make wallpaper setting more tolerant

---

debian/control

This dependency isn't used by the package any more.
cc @Ealdwulf @skarbat @alex5imon

debian: Removing unused dependency

---

kano_settings/config_file.py
kano_settings/locale.py
kano_settings/screens.py
kano_settings/system/locale.py
kano_settings/system/supported_locales.py
tests/i18n/test_locale.py

Adds the Locale screen (not visible from the home screen but available with `kano-settings locale`.
Also adds a few useful locale functions
cc @convolu @pazdera @carolineclark

Locale screen

---

debian/control
kano_settings/parental_config.py
kano_settings/set_display.py

Adds tracking for both screen modes and parental lock
Related to: https://github.com/KanoComputing/peldins/issues/1910
cc @carolineclark @alex5imon

Settings tracking

---

lxpanel-plugin-internet/kano_internet.c

Added monitoring to the plugin

---

bin/kano-wifi
kano_settings/set_about.py
kano_settings/set_wifi.py
kano_settings/system/proxy.py

Changes to open the default system browser, which will now be Midorid. Goes along with this changeset: https://github.com/KanoComputing/kano-toolset/pull/142

starting the default browser instead of chromium

---

debian/control
kano_settings/set_wallpaper.py

This will allow us deliver wallpapers to the OS through the content
api.
cc @convolu @alex5imon

appearance: Adding support for the 'wallpapers' co

---

kano_settings/system/advanced.py

* Split the functions into single user or everyone, so they can be called
from kano-settings as well as kano-init during the new user creation
cc @alex5imon

changed youtube parental functions to be called generically

---

kano_settings/config_file.py
kano_settings/set_display.py
kano_settings/system/display.py

180 Flip Screen button for the Screen kit.
@alex5imon @carolineclark 
third time's the charm

180 Flip Screen button for the Screen kit.

---

kano_settings/parental_config.py
kano_settings/set_advanced.py
kano_settings/system/advanced.py
media/kano-settings/CSS/style.css

https://github.com/KanoComputing/peldins/issues/1971

Parental fix

---

kano_settings/system/audio.py

New Master fader

---

kano_settings/system/audio.py

Fixing amixer output

---

kano_wifi_gui/NetworkScreen.py
kano_wifi_gui/PasswordScreen.py

- Fixes a copy showing `You\'re`
@alex5imon is this alright?

Fixed a typo showing slash

---

bin/kano-wifi-gui
kano_wifi_gui/PasswordScreen.py
kano_wifi_gui/Template.py

https://github.com/KanoComputing/peldins/issues/2112

Enter key can be used to pass screens in WiFi GUI

---

bin/kano-wifi-gui
debian/control
kano_wifi_gui/ConnectToNetwork.py
kano_wifi_gui/NetworkScreen.py
kano_wifi_gui/PasswordScreen.py
kano_wifi_gui/RefreshNetworks.py
kano_wifi_gui/SpinnerScreen.py
kano_wifi_gui/Template.py
kano_wifi_gui/WhiteButton.py
kano_wifi_gui/ctl.py
kano_wifi_gui/wifi_window.py

Despite some separation between the two, lots of non-command line code
was still within the executable. Complete the full separation.
@pazdera @convolu What do you think?

WiFi GUI: Separate library from executable

---

debian/changelog
kano_settings/system/wallpaper.py

We need to set the background in the init flow based on what the user chooses in the picker. This will allow us to do that.
Related to: https://github.com/KanoComputing/peldins/issues/2212
cc @alex5imon @tombettany @convolu @skarbat

wallpapers: Adding a getter to the wallpaper API

---

kano_settings/set_display.py

Related to: https://github.com/KanoComputing/peldins/issues/2197
The overscan limits in settings were set to 100. This change makes it dynamic based on the system resolution (maximum cutoff is 1/3 of the screen at each edge).
cc @alex5imon @convolu @Ealdwulf @skarbat @tombettany

Increase the overscan limits

---

kano_wifi_gui/PasswordScreen.py

Related to: https://github.com/KanoComputing/peldins/issues/2245
cc @alex5imon @convolu @tombettany @skarbat

wifi-gui: Trigger an event on success

---

kano_settings/set_wallpaper.py

Picking a wallpaper is now the first step of building a desktop. So it doesn't make sense to say that you've just built it.
cc @alex5imon @neue @convolu @tombettany

Boot wallpaper selection copy change

---

kano_settings/boot_config.py

This PR  fixed the traceback seen from kano-settings-onboot. This was logically safe, but would cause unnecessary  writes to `/boot/config.txt` which should be avoided (as well as noise in the logs).
@convolu @tombettany

Change remove_noobs_defaults() to only move to r/w state when it actually needs to

---

debian/control
kano_settings/set_notifications.py

Related to https://github.com/KanoComputing/Kerberos/issues/4

Moved from hardware dependent feature to performance dependent

---

bin/kano-wifi
debian/control
etc/network/interfaces
etc/rc.network
kano_wifi_gui/ctl.py
kano_wifi_gui/wifi_window.py
lxpanel-plugin-internet/Makefile
lxpanel-plugin-internet/kano_internet.c

To support variable network interfaces, don't hard-code the network
interface to use.
To be merged after release of v2.3.0.
cc @Ealdwulf @convolu @radujipa

WiFi: Rely on libs module for wlan interface

---

kano_settings/system/display.py

Error making directory for backup of X11 config file.

Fix type of basename for dirname.

---

.gitignore
kano_settings/boot_config.py
kano_settings/config_file.py
kano_settings/default.py
kano_settings/set_overclock.py
kano_settings/system/about.py
kano_settings/system/boards/__init__.py
kano_settings/system/boards/rpi_1.py
kano_settings/system/boards/rpi_2.py
kano_settings/system/overclock.py
kano_settings/system/overclock_chip_support.py

Abstract board settings to make it simple to support boards with other
settings.
Requires: https://github.com/KanoComputing/kano-toolset/pull/193
First draft and not tested yet but what do you guys think of the approach?
@convolu @radujipa @Ealdwulf

Boards: Make detection systems hardware agnostic

---

etc/init.d/kano-settings

@alex5imon Add capabilities dropped by noobs.

Add noobs fix.

---

bin/kano-settings-cli
kano_settings/system/display.py

@tombettany this will allow us to set the new overscan values persistently.

Added CLI option to set overscan values

---

bin/kano-settings-cli

The CLI tool already included a command to set the audio mode however
this was unimplemented and hence did nothing when called. Connect this
command with the associated action.
cc @skarbat @Ealdwulf

CLI: Implement setting audio

---

boot_default/config.txt

@alex5imon This fixes the audio issue with the new kernel.
Sill merge if it went okay at the workshop.

Add audio setting for kernel 4.4

---

kano_settings/system/audio.py
kano_settings/system/display.py

* Avoid calling tvservice when the audio module is imported
* Clarified code, return a meaningul response after setting audio output

Fixes for tvservice

---

kano_settings/set_audio.py
kano_settings/system/audio.py

Fixes broken import and caches result of is_hdmi_audio_import()
@skarbat

Fix broken import. Also avoid calling tvservice more than once.

---

tests/boot_config/test_config.py

This should fix a test failure due to https://github.com/KanoComputing/kano-settings/pull/377
@skarbat @tombettany

Fix to only test restore config if backup has been performed first.

---

boot_default/config.txt
kano_settings/boot_config.py

Add changes to config for make-light on the pi3, and comments in methods which are now used in the updater.
For https://github.com/KanoComputing/peldins/issues/2369
@alex5imon @tombettany This is the equivalent change needed for the image build.

Pi3 fix for uart

---

boot_default/config.txt

Test audio dither setting for tomorrow's image, for https://github.com/KanoComputing/peldins/issues/2384#issuecomment-224351150

Switch off audio dither to reduce noise.

---

debian/control
debian/kano-settings.install
etc/polkit-1/localauthority/50-local.d/10-udisks.pkla

Related to https://github.com/KanoComputing/peldins/issues/2378
cc @skarbat @Ealdwulf

Added permissions config to enable USB drive auto-mount

---

kano_wifi_gui/wifi_window.py

Related to https://trello.com/c/nm7vLA0q/289-settings-no-wifi-dongle-plugged-in-try-again-dialogue-not-working-worked-by-relaunching
@Ealdwulf this look alright?

Fixed non-updating WiFi dongle setup screen when Retrying

---

boot_default/config.txt
kano_settings/system/boot_config/boot_config_parser.py
tests/boot_config/boot_config_parser.py

This PR should fix https://trello.com/c/cDOFycaq
Here, I only try to make sure all filters are in the form the module understands. I will put in another ticket to enhance it to understand filters properly.
@radujipa @rcocetta @tombettany

Terminate filters

---

boot_default/config.txt

This PR add the other screen kit EDID. @tombettany

Add second screen kit ID

---

etc/init.d/kano-settings
po/es_AR.po

Provide kit bootup message in Spanish

---

WHITELIST

Propagate #484 + #482 to jessie

Propagate changes to WHITELIST from master.
